"""Stage 8 results draft (exploratory, amendments A7-A9), numbers read from outputs_v3/."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
V3 = ROOT / "outputs_v3"
A7, A8, A9, DG = V3 / "anticipation", V3 / "anticipation_a8", V3 / "anticipation_a9", V3 / "diagnostics"
REPORT = V3 / "reports" / "stage8_anticipation_draft.md"


def rd(path: Path, **kw) -> pd.DataFrame:
    return pd.read_csv(path, **kw)


def ci(est, lo, hi, d=4) -> str:
    return f"{est:+.{d}f} [{lo:+.{d}f}, {hi:+.{d}f}]"


def pv(p: float) -> str:
    return "<0.001" if p < 0.001 else f"{p:.3f}"


def hyp_table(h: pd.DataFrame) -> str:
    h = h[h.test.str.startswith("H")]
    lines = ["| Test | Estimate | 95% CI | p (one-sided) | p (Holm) | Survives Holm |", "|---|---|---|---|---|---|"]
    for r in h.itertuples():
        is_rmse = "DM" in r.test
        est = f"rel. RMSE {r.estimate:.3f}" if is_rmse else f"{r.estimate:+.4f}"
        c = "–" if is_rmse else f"[{r.ci_low:+.4f}, {r.ci_high:+.4f}]"
        lines.append(f"| {r.test} | {est} | {c} | {pv(r.p_one_sided)} | {pv(r.p_holm)} | "
                     f"{'**yes**' if r.survives_holm else 'no'} |")
    return "\n".join(lines)


def main() -> None:
    # diagnostics
    lag = rd(DG / "lag_correlation.csv").set_index(["series", "months_before_interview"]).correlation
    ceil = rd(DG / "monthly_signal_ceiling.csv").set_index("predictor").auc
    v2h = rd(DG / "v2_forecast_by_horizon.csv").set_index(["series", "h"]).rel_rmse_vs_naive
    # A7
    pa = rd(A7 / "price_accuracy.csv").set_index(["series", "period"])
    ph = rd(A7 / "price_accuracy_by_horizon.csv").set_index(["series", "h"]).rel_rmse
    d7 = rd(A7 / "delta_auc.csv").set_index(["contrast", "subset"])
    m7 = rd(A7 / "metrics.csv").set_index(["model", "subset"])
    c7 = rd(A7 / "calibration.csv").set_index("model")
    pr7 = rd(A7 / "prevalence_by_year.csv").set_index("interview_year_t1")
    fl = rd(A7 / "sample_flow.csv")
    n = lambda s: int(fl[fl.step.str.strip() == s].n.iloc[0])  # noqa: E731
    # A8
    h8 = rd(A8 / "hypotheses.csv")
    fc8 = rd(A8 / "forward_chain_auc.csv").set_index(["stratum", "subset"])
    fold = rd(A8 / "fold_auc.csv")
    mae = rd(A8 / "prevalence_mae.csv").set_index("design")
    c8 = rd(A8 / "calibration.csv").set_index("model")
    pe8 = rd(A8 / "prevalence_error.csv")
    pe8 = pe8[pe8.design == "A6 split"].set_index("interview_year_t1")
    dm8 = rd(A8 / "decision_metrics.csv").set_index("model")
    # A9
    h9 = rd(A9 / "hypotheses.csv")
    pa9 = rd(A9 / "price_accuracy_cap.csv").set_index(["series", "period", "comparison"])
    ph9 = rd(A9 / "price_accuracy_cap_by_horizon.csv").set_index(["series", "h"])
    fc9 = rd(A9 / "forward_chain_auc.csv").set_index("stratum")
    c9 = rd(A9 / "calibration.csv").set_index("model")

    def d(c, s, tab=d7):
        r = tab.loc[(c, s)]
        return ci(r.delta_auc, r.ci_low, r.ci_high)

    CR = "cap regime (T >= 2019-03)"
    all_vs_naive = pd.concat([
        pa.xs("all 2009+", level="period").loc[["gas", "electricity"], "rel_rmse"],
        rd(A8 / "price_shock_accuracy.csv").query("stratum == 'shock'").set_index("series").rel_rmse,
        pa9.xs("F_cap vs no-change", level="comparison").rel_rmse,
        pa9.xs("F_futures vs no-change", level="comparison").xs(CR, level="period").rel_rmse])
    p_all = pd.concat([
        pa.xs("all 2009+", level="period").loc[["gas", "electricity"], "dm_p"] / 2,  # two-sided -> one-sided (all favour the forecast)
        rd(A8 / "price_shock_accuracy.csv").query("stratum == 'shock'").p_one_sided,
        pa9.xs("F_cap vs no-change", level="comparison").p_one_sided,
        pa9.xs("F_futures vs no-change", level="comparison").xs(CR, level="period").p_one_sided])

    text = f"""# Stage 8 (exploratory): anticipatory burden projection

*Generated by `scripts/stage8_draft.py`; every number comes from `outputs_v3/`. Draft for the author's rewrite.*

> **Status.** Stage 8 is **exploratory and post hoc**. It was designed after the pre-specified v2 results
> (Stages 2–6) were seen. Each round was fixed in writing before its code ran: amendments A7, A8 and A9 in
> `analysis_plan_rerun.md`, each with its own decision rule. Stage 8 does **not** replace any pre-specified
> result. The v2 verdicts (H2, H5, and the rest) stand as reported.

## 1. Why the pre-specified FES could not detect anticipation

The v2 FES added nothing to next-wave prediction (Stage 6: ΔAUC −0.0006). Diagnostics
(`outputs_v3/diagnostics/`) show that this follows from the design rather than from noise.

1. **Timing.** The outcome is fuel spend over the 12 months *before* the interview. The FES forecasts
   the months *after* it. The monthly vulnerability rate correlates most strongly with retail gas price
   growth 9–12 months earlier (r = {lag[('gas', 9)]:.2f} at 9 months, {lag[('gas', 12)]:.2f} at 12). It
   correlates negatively with growth 6 months later (r = {lag[('gas', -6)]:.2f}). Electricity shows the
   same pattern ({lag[('electricity', 12)]:.2f} at 12 months, {lag[('electricity', -6)]:.2f} at −6).
2. **Growth vs level.** The FES measures price *growth*. Burden depends on the price *level*. After
   the 2022 peak, growth turned negative while bills stayed high, so the FES signalled relief while
   vulnerability was at its highest.
3. **A national monthly signal cannot rank households.** The FES is one value per month, the same for
   every household interviewed that month. In the validation waves (n, o), even the *true* monthly
   vulnerability rate used as the only predictor reaches AUC {ceil.iloc[0]:.3f}. The FES itself reaches
   {ceil.iloc[1]:.3f}.
4. **The forecasts added no forward information.** The selected v2 models were worse than no-change at
   1–3 months ahead (relative RMSE {v2h[('gas', 1)]:.2f}–{v2h[('gas', 3)]:.2f} for gas and
   {v2h[('electricity', 1)]:.2f}–{v2h[('electricity', 3)]:.2f} for electricity). At longer horizons they
   won mainly by pulling towards the historical mean after the 2022 spike.

## 2. Design

The forecast's role changes: it is no longer a national predictor but is used to **project each
household's own next burden**, using only information available at its wave-t interview month T.

| Step | Content (information set at T) |
|---|---|
| 1. Price level | Log retail CPI level for gas (D7DU), electricity (D7DT) and liquid fuels (D7DV). Direct per-horizon OLS on NBP gas futures (Brent for oil), expanding window. CPI known to T−2, markets to T−1. The Energy Price Guarantee is applied once announced. A9 adds Ofgem's cap levels, counted as known from the month before each cap starts (never earlier than the announcement). |
| 2. Fuel mix | Wave-t spend is split into gas, electricity, oil and other fuel. Price multiplier = share-weighted ratio of mean price over the next 12 months to mean price over the last 12. |
| 3. Income | Labour income × the latest average-earnings growth. Benefit and pension income × the statutory CPI uprating known at T. Support-scheme payments are a sensitivity. |
| 4. Projection | Projected burden b̂ = spend × multiplier ÷ projected income, with the A1 guards. The structural probability P(b̂ ≥ 10%) is reported. |
| 5. Evaluation | A6 linking and split: training a→b … l→m ({n('training'):,} transitions), validation m→n and n→o ({n('validation'):,}; of which {n('validation incident (not vulnerable at t)'):,} were not vulnerable at t). A8/A9 add forward-chaining: each transition from e→f to n→o is predicted by models fitted only on earlier transitions. PSU bootstrap (2,000 replicates); Holm correction within each amendment. |

**Key contrast.** A_fut (projection with the price forecast) vs A_naive (the same projection with prices held
at their last known level). The difference isolates the value of the *price forecast*. Most tests use
**newly vulnerable** households (not vulnerable at t), where anticipation matters most.

## 3. Results

### 3.1 Price forecasts (step 1)

| Comparison (window-ratio RMSE) | Gas | Electricity |
|---|---|---|
| Futures vs no-change, all origins 2009+ (A7) | {pa.loc[('gas', 'all 2009+'), 'rel_rmse']:.3f} (p = {pa.loc[('gas', 'all 2009+'), 'dm_p']:.3f}, two-sided) | {pa.loc[('electricity', 'all 2009+'), 'rel_rmse']:.3f} (p = {pa.loc[('electricity', 'all 2009+'), 'dm_p']:.3f}, two-sided) |
| Futures vs no-change, 2009–2020 origins | {pa.loc[('gas', '2009-2020'), 'rel_rmse']:.3f} | {pa.loc[('electricity', '2009-2020'), 'rel_rmse']:.3f} |
| Futures vs no-change, 2021+ origins | {pa.loc[('gas', '2021+'), 'rel_rmse']:.3f} (p = {pa.loc[('gas', '2021+'), 'dm_p']:.3f}) | {pa.loc[('electricity', '2021+'), 'rel_rmse']:.3f} (p = {pa.loc[('electricity', '2021+'), 'dm_p']:.3f}) |
| Caps + futures vs no-change, 2019+ (A9) | {pa9.loc[('gas', CR, 'F_cap vs no-change'), 'rel_rmse']:.3f} | {pa9.loc[('electricity', CR, 'F_cap vs no-change'), 'rel_rmse']:.3f} |
| Caps + futures vs caps then flat, 2019+ (A9) | {pa9.loc[('gas', CR, 'F_cap vs F_capflat'), 'rel_rmse']:.3f} | {pa9.loc[('electricity', CR, 'F_cap vs F_capflat'), 'rel_rmse']:.3f} |

- **By horizon (A7):** the futures forecast beats no-change at every horizon from 1 to 13 months. Gas
  relative RMSE is {ph[('gas', 1)]:.2f} at 1 month and {ph[('gas', 6)]:.2f} at 6. The v2 models were
  3–4× *worse* than no-change at 1–3 months.
- **Announced caps (A9):** these make short horizons nearly exact. Gas relative RMSE vs no-change is
  {ph9.loc[('gas', 1), 'rel_cap_vs_naive']:.2f} at 1 month and {ph9.loc[('gas', 3), 'rel_cap_vs_naive']:.2f}
  at 3; electricity is {ph9.loc[('electricity', 1), 'rel_cap_vs_naive']:.2f} and
  {ph9.loc[('electricity', 3), 'rel_cap_vs_naive']:.2f}. Over the full 12-month bill window, the caps add
  little beyond the futures.
- **Across all {len(all_vs_naive)} tested comparisons with no-change:** relative RMSE ranges from
  {all_vs_naive.min():.2f} to {all_vs_naive.max():.2f}, always in favour of the forecast. One-sided p ranges
  from {p_all.min():.3f} to {p_all.max():.3f}. **None survives multiple-testing correction.** Monthly
  origins overlap, so the cap era (79 origins) carries roughly 6–7 independent years of information.
  That is too little to establish an improvement of about 30% at conventional significance.

![Figure 8-1](../anticipation/figures/price_window_ratio.png)

*Figure 8-1. Price change over the next 12 months vs the last 12: realised, futures forecast, and no-change,
by forecast origin.*

![Figure 8-2](../anticipation_a9/figures/cap_window_ratio.png)

*Figure 8-2. As Figure 8-1 from 2018, adding the forecast that uses announced caps.*

### 3.2 Household identification: A7 (A6 split)

| Model (validation, newly vulnerable) | AUC [95% CI] |
|---|---|
| P0: current burden (A6 benchmark) | {m7.loc[('P0 (A6 benchmark)', 'incident'), 'auc']:.3f} [{m7.loc[('P0 (A6 benchmark)', 'incident'), 'auc_ci_low']:.3f}, {m7.loc[('P0 (A6 benchmark)', 'incident'), 'auc_ci_high']:.3f}] |
| P3 = P0 + P1 | {m7.loc[('P3 = P0 + P1', 'incident'), 'auc']:.3f} [{m7.loc[('P3 = P0 + P1', 'incident'), 'auc_ci_low']:.3f}, {m7.loc[('P3 = P0 + P1', 'incident'), 'auc_ci_high']:.3f}] |
| A_naive: projection, no-change prices | {m7.loc[('A_naive', 'incident'), 'auc']:.3f} [{m7.loc[('A_naive', 'incident'), 'auc_ci_low']:.3f}, {m7.loc[('A_naive', 'incident'), 'auc_ci_high']:.3f}] |
| A_fut: projection, forecast prices | {m7.loc[('A_fut', 'incident'), 'auc']:.3f} [{m7.loc[('A_fut', 'incident'), 'auc_ci_low']:.3f}, {m7.loc[('A_fut', 'incident'), 'auc_ci_high']:.3f}] |
| A_full = A_fut + P1 | {m7.loc[('A_full = A_fut + P1', 'incident'), 'auc']:.3f} [{m7.loc[('A_full = A_fut + P1', 'incident'), 'auc_ci_low']:.3f}, {m7.loc[('A_full = A_fut + P1', 'incident'), 'auc_ci_high']:.3f}] |
| A_oracle: realised prices (upper bound) | {m7.loc[('A_oracle (realised prices; bound)', 'incident'), 'auc']:.3f} |

- **Value of the price forecast** (A_fut − A_naive): {d('A_fut - A_naive', 'incident')} for newly
  vulnerable households; {d('A_fut - A_naive', 'all')} for all households.
- **Against the best v2 model** (A_full − P3): {d('A_full = A_fut + P1 - P3 = P0 + P1', 'incident')} for
  newly vulnerable households.
- **Upper bound:** perfect price foresight (A_oracle − A_naive) gives
  {d('A_oracle (realised prices; bound) - A_naive', 'incident')}. The forecast realises about
  {d7.loc[('A_fut - A_naive', 'incident'), 'delta_auc'] / d7.loc[('A_oracle (realised prices; bound) - A_naive', 'incident'), 'delta_auc']:.0%}
  of that.
- **Support schemes** (sensitivity): subtracting the Energy Bills Support Scheme and adding the pensioner
  payment *lowers* AUC ({d('A_fut_support - A_fut', 'incident')}). Reported spend probably does not net
  out the rebate.
- **A7 decision rule: not met.** Criterion (ii), the household gain, was met. Criterion (i), futures
  significantly beating no-change over 2009+, was not.

### 3.3 Is the gain concentrated where anticipation should matter? A8 (forward-chained)

{hyp_table(h8)}

| Forward-chained, newly vulnerable | n | AUC A_naive | AUC A_fut | Δ (A_fut − A_naive) [95% CI] |
|---|---|---|---|---|
| Shock origins (forecast bill change ≥ 10%) | {int(fc8.loc[('shock', 'incident'), 'n']):,} | {fc8.loc[('shock', 'incident'), 'auc_A_naive']:.4f} | {fc8.loc[('shock', 'incident'), 'auc_A_fut']:.4f} | {ci(fc8.loc[('shock', 'incident'), 'delta_fut_vs_naive'], fc8.loc[('shock', 'incident'), 'ci_low'], fc8.loc[('shock', 'incident'), 'ci_high'])} |
| Calm origins | {int(fc8.loc[('calm', 'incident'), 'n']):,} | {fc8.loc[('calm', 'incident'), 'auc_A_naive']:.4f} | {fc8.loc[('calm', 'incident'), 'auc_A_fut']:.4f} | {ci(fc8.loc[('calm', 'incident'), 'delta_fut_vs_naive'], fc8.loc[('calm', 'incident'), 'ci_low'], fc8.loc[('calm', 'incident'), 'ci_high'])} |

- **Shock vs calm:** the gain is about {fc8.loc[('shock', 'incident'), 'delta_fut_vs_naive'] / fc8.loc[('calm', 'incident'), 'delta_fut_vs_naive']:.0f}×
  larger at shock origins than at calm ones, as the anticipation hypothesis predicts.
- **By transition:** the largest gains are l→m ({fold.set_index('transition').loc['l->m', 'gain_inc_fut_vs_naive']:+.4f})
  and n→o ({fold.set_index('transition').loc['n->o', 'gain_inc_fut_vs_naive']:+.4f}). Transitions with few
  shock interviews show about zero.
- **Exception:** m→n is mostly shock interviews but gains only
  {fold.set_index('transition').loc['m->n', 'gain_inc_fut_vs_naive']:+.4f}.
- **Screening all households (H8.4):** when the top 10% of all households are flagged, the already
  vulnerable dominate the list. The forecast finds {int(dm8.loc['A_fut', 'incident_found'])} of
  {int(dm8.loc['A_fut', 'incident_positives']):,} newly vulnerable households, against
  {int(dm8.loc['P0', 'incident_found'])} for P0. The difference is not significant.
- **Separate terms (H8.3):** entering current burden, price multiplier and income change separately
  improves calibration most. The calibration intercept is {c8.loc['A_sep_fut', 'intercept']:+.2f}
  against {c8.loc['P0', 'intercept']:+.2f} for P0. Mean absolute error of yearly prevalence (forward-chained)
  is {100 * mae.loc['forward-chained', 'A_sep_fut']:.1f} percentage points against
  {100 * mae.loc['forward-chained', 'P0']:.1f} for P0. Predicted 2023 prevalence is
  {100 * pe8.loc[2023, 'A_sep_fut']:.1f}%, against {100 * pe8.loc[2023, 'actual']:.1f}% actual and
  {100 * pe8.loc[2023, 'P0']:.1f}% from P0. Ranking, however, is worse than the single projected burden.
- **A8 decision rule: not met.** H8.1 survives; the price tests H8.2a/b do not.

![Figure 8-3](../anticipation_a8/figures/fold_gain.png)

*Figure 8-3. AUC gain from the price forecast among newly vulnerable households, by forward-chained
validation transition (orange: most wave-t interviews at shock origins).*

### 3.4 Adding announced caps: A9

{hyp_table(h9)}

- **Household gain (H9.3):** in the cap era the household gain is
  {fc9.loc[CR, 'delta_A_cap_vs_A_naive']:+.4f} {fc9.loc[CR, 'ci_A_cap_vs_A_naive']}. Before 2019 it is
  {fc9.loc['pre-cap (T < 2019-03)', 'delta_A_cap_vs_A_naive']:+.4f}.
- **Caps vs futures alone:** caps add little over the futures-only projection
  ({fc9.loc[CR, 'delta_A_cap_vs_A_fut']:+.4f} {fc9.loc[CR, 'ci_A_cap_vs_A_fut']}).
- **Calibration:** the cap projection has the best calibration-in-the-large of any model:
  {c9.loc['A_cap', 'intercept']:+.2f}, against {c9.loc['P0', 'intercept']:+.2f} for P0 on the same sample.
- **A9 decision rule: not met.** H9.3 survives; H9.1a/b do not.

## 4. Verdict

| Claim | Evidence | Status |
|---|---|---|
| Projected anticipatory price information improves identification of *newly* vulnerable households | Significant in A7 (split), A8 (forward-chained, shock origins) and A9 (cap era); Holm-corrected where pre-specified | **Supported (exploratory, replicated in three designs)** |
| The gain is concentrated in periods of forecast price change | Shock vs calm contrast in A8; cap era vs pre-cap in A9 | **Supported (exploratory)** |
| Projection improves predicted prevalence in the crisis | Calibration intercept and yearly prevalence error (A7–A9) | **Supported (descriptive, not tested)** |
| The price forecast is significantly more accurate than no-change | Relative RMSE {all_vs_naive.min():.2f}–{all_vs_naive.max():.2f} in all comparisons; none survives correction | **Not established (direction consistent, underpowered)** |
| Anticipation changes who a screen of all households reaches | H8.4 | **Not supported** |
| Pre-specified decision rules A7, A8, A9 | Each failed on its price-accuracy criterion | **Not met** |

**Suggested wording for the thesis.**

> Anticipatory price information (wholesale futures and announced price caps) is available before
> households are billed. Projected onto each household's own fuel mix and income, it gives a small but
> statistically robust improvement in identifying households that newly become vulnerable. This was
> replicated across three designs, and the gain is concentrated in periods of price change, as the
> anticipation hypothesis predicts. The projection also brings predicted crisis prevalence much closer to
> the observed rate. The price forecasts had {100 * (1 - all_vs_naive.max()):.0f}–{100 * (1 - all_vs_naive.min()):.0f}% lower error than a no-change forecast in every
> comparison. With only about seven independent years of data since the 2019 cap, this superiority could not
> be established at conventional significance after multiple-testing correction. All Stage 8 analyses are
> exploratory and were specified after the pre-registered results were seen.

## 5. Limitations

- **Post hoc.** Three rounds of amendments after the v2 results were seen. Each was fixed before its code
  ran, but the family of analyses is exploratory. A confirmatory test needs new data (a new UKHLS wave
  and further cap periods) under this fixed design.
- **Small effects.** AUC gains are about 0.004–0.006. Current burden remains the dominant predictor.
- **Measured outcome.** Spend is self-reported over the previous 12 months, and whether reported bills
  are net of rebates is unknown (the support-scheme sensitivity lowered AUC).
- **Approximations.**
  - The Price Guarantee is scaled by typical-bill ratios.
  - The 2013–15 benefit cap and the 2016–19 freeze are not modelled.
  - Means-tested cost-of-living payments are not modelled.
  - The t+1 interview is assumed at T+12.
- **Cap timing rule.** The conservative rule (cap known from the month before it starts) sometimes misses
  policy announced earlier in that month (Energy Price Guarantee, September 2022; Budget extension,
  March 2023).
- **Structural probability.** P(b̂ ≥ 10%) ranks as well as the fitted models but over-predicts
  prevalence (calibration intercept {c7.loc['p_struct', 'intercept']:+.2f}).

## 6. Reproduce

```
python scripts/stage8_diagnostics.py      # section 1
python scripts/stage8_price_forecast.py   # A7 step 1
python scripts/stage8_anticipation.py     # A7 steps 2-5 (~15 min)
python scripts/stage8b_conditional.py     # A8 (~30 min)
python scripts/stage8c_cap.py             # A9 (~30 min)
python scripts/suppress_small_cells.py    # disclosure control, then --check
python scripts/stage8_draft.py            # this draft
```

External inputs (`data/raw/anticipation/`, not tracked):
- ONS MM23 CPI indices D7DU, D7DT, D7DV, D7DW, D7BT;
- ONS AWE KAB9;
- FRED MCOILBRENTEU;
- Ofgem *Default tariff cap level* v1.31;
- the existing NBP futures file in `data/raw/`.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(text)
    print(f"wrote {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
