"""Stage 6 results draft (H5), numbers read from outputs_v2/stage6/."""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src.paths import OUTPUTS_DIR  # noqa: E402

D = OUTPUTS_DIR / "stage6"


def main() -> None:
    m = pd.read_csv(D / "metrics.csv").set_index(["model", "metric"])
    cal = pd.read_csv(D / "calibration.csv").set_index("model")
    dl = pd.read_csv(D / "delta_auc.csv").set_index("comparison")
    fl = pd.read_csv(D / "sample_flow.csv")
    fl["n"] = pd.to_numeric(fl["n"], errors="coerce")
    p3 = pd.read_csv(D / "posthoc_p3_metrics.csv").set_index(["model", "metric"])
    p3d = pd.read_csv(D / "posthoc_p3_delta_auc.csv").set_index("comparison")
    p2b = pd.read_csv(D / "p2b_sensitivity.csv").set_index("model")
    n = lambda step: int(fl[fl.step.str.strip().str.startswith(step)].n.iloc[0])  # noqa: E731
    e = lambda mod, k: m.loc[(mod, k)]  # noqa: E731
    ci = lambda r, pct=False: (f"{100*r.estimate:.1f}% ({100*r.ci_low:.1f}–{100*r.ci_high:.1f})" if pct  # noqa: E731
                               else f"{r.estimate:.3f} ({r.ci_low:.3f}–{r.ci_high:.3f})")
    P3 = "P3 (post-hoc) = P0 + P1"
    text = f"""# Stage 6 draft: next-wave prediction (H5)

*Generated by `scripts/stage6_draft.py`; every number comes from `outputs_v2/stage6/`. Draft for the author's rewrite.*

**Design.** Households are linked across consecutive waves by the reference person. Models are trained
on transitions a→b to l→m and validated on the two latest transitions (m→n, n→o), which were not used in
fitting. All three models use one common sample ({n('common sample'):,} transitions: {n('training'):,} training,
{n('validation transitions'):,} validation; validation prevalence {fl[fl.step.str.contains('prevalence')].n.iloc[0]:.1f}%).
Predictors are standardised with training statistics only. P0 (this wave's fuel burden) is a benchmark;
P1 uses household predictors (financial difficulty, GHQ distress, financial expectations, age, central
heating, family type, worklessness and the four resource composites); P2 adds the growth-only FES forecast
for the household's next interview month (December vintage before that year).

**H5 verdict: partially supported.** Next-wave fuel vulnerability can be predicted before it is observed
with moderate discrimination: P1 reaches ROC-AUC {ci(e('P1','auc'))} and PR-AUC {e('P1','prauc').estimate:.3f}
(no-skill baseline {fl[fl.step.str.contains('prevalence')].n.iloc[0]/100:.3f}). But the forecast adds nothing and the
household model does not beat the simple benchmark:

- Adding FES: no improvement (ΔAUC {dl.loc['P2 - P1','delta_auc']:.4f}); P2 AUC {ci(e('P2','auc'))}.
  Adding FES Delta observed at wave t as well (P2b) also gives no improvement
  (AUC {p2b.loc['P2b','auc']:.3f} vs {p2b.loc['P1 (P2b sample)','auc']:.3f} for P1 on the same sample).
- The benchmark, this wave's fuel burden alone (P0), discriminates better: AUC {ci(e('P0','auc'))};
  ΔAUC P1 − P0 = {dl.loc['P1 - P0','delta_auc']:.3f} ({dl.loc['P1 - P0','ci_low']:.3f} to {dl.loc['P1 - P0','ci_high']:.3f}).
- Among the 10% of households with the highest predicted risk, P0 captures {ci(e('P0','sens10'), True)} of next-wave
  cases with PPV {ci(e('P0','ppv10'), True)}; P1 captures {ci(e('P1','sens10'), True)} with PPV {ci(e('P1','ppv10'), True)}.
- Calibration: all models under-predict risk in the validation (crisis) waves (calibration-in-the-large
  {cal.loc['P0','intercept']:.2f} for P0, {cal.loc['P1','intercept']:.2f} for P1, {cal.loc['P2','intercept']:.2f} for P2, log-odds); P1 and P2 rank
  households with little overfitting (slope {cal.loc['P1','slope']:.2f} and {cal.loc['P2','slope']:.2f}), P0 is over-dispersed
  (slope {cal.loc['P0','slope']:.2f}).

**Post-hoc (exploratory, not pre-specified).** Combining the benchmark with the household predictors
(P3 = P0 + P1) gives AUC {ci(p3.loc[(P3,'auc')])}: no gain over P0 alone (ΔAUC {p3d.loc['P3 - P0','delta_auc']:.4f},
{p3d.loc['P3 - P0','ci_low']:.4f} to {p3d.loc['P3 - P0','ci_high']:.4f}). Top-10% sensitivity {ci(p3.loc[(P3,'sens10')], True)}, PPV
{ci(p3.loc[(P3,'ppv10')], True)}.

**Reading.** For early warning, the most informative signal is a household's current fuel burden; the
household profile adds little beyond it, and the national forecast adds nothing to household-level
prediction. The forecast's role is timing context, not household targeting.
"""
    (OUTPUTS_DIR / "reports" / "stage6_prediction_draft.md").write_text(text)


if __name__ == "__main__":
    main()
